// =============================================
// 中1数学RPG学習アプリ - 問題データ (50問)
// =============================================
const QUESTIONS = [
  // ===== 正負の数 (easy: 1-8, normal: 9-11) =====
  {
    "id": 1,
    "unit": "正負の数",
    "difficulty": "easy",
    "question": "5 + (−3) はいくつ？",
    "choices": ["2", "−2", "8", "−8"],
    "answer": "2",
    "explanation": "正の数5に負の数−3をたすと、5−3＝2になります。",
    "exp": 10,
    "levelRecommended": 1,
    "enemyType": "スライム",
    "battleMessage": "スライムがあらわれた！正しい答えでこうげきしよう！"
  },
  {
    "id": 2,
    "unit": "正負の数",
    "difficulty": "easy",
    "question": "(−4) + (−2) はいくつ？",
    "choices": ["6", "−6", "−2", "2"],
    "answer": "−6",
    "explanation": "マイナスどうしをたすと、絶対値を足してマイナスになります。4＋2＝6なので −6です。",
    "exp": 10,
    "levelRecommended": 1,
    "enemyType": "スライム",
    "battleMessage": "スライムが「冷たいしぶき」を使おうとしている！魔法で止めよう！"
  },
  {
    "id": 3,
    "unit": "正負の数",
    "difficulty": "easy",
    "question": "3 − 7 はいくつ？",
    "choices": ["4", "−4", "10", "−10"],
    "answer": "−4",
    "explanation": "3から7をひくと、小さい方から大きい方を引くのでマイナスになります。7−3＝4なので、答えは −4。",
    "exp": 10,
    "levelRecommended": 1,
    "enemyType": "コウモリ",
    "battleMessage": "コウモリが飛んできた！正確に答えて撃ち落とせ！"
  },
  {
    "id": 4,
    "unit": "正負の数",
    "difficulty": "easy",
    "question": "(−2) × 3 はいくつ？",
    "choices": ["6", "−6", "−1", "5"],
    "answer": "−6",
    "explanation": "負の数に正の数をかけると答えはマイナスになります。2×3＝6なので、−6です。",
    "exp": 10,
    "levelRecommended": 1,
    "enemyType": "コウモリ",
    "battleMessage": "コウモリの群れがあらわれた！一撃で仕留めよう！"
  },
  {
    "id": 5,
    "unit": "正負の数",
    "difficulty": "easy",
    "question": "(−8) ÷ (−4) はいくつ？",
    "choices": ["2", "−2", "4", "−4"],
    "answer": "2",
    "explanation": "負の数どうしを割ると答えはプラスになります。8÷4＝2なので、答えは 2。",
    "exp": 10,
    "levelRecommended": 1,
    "enemyType": "ゴブリン",
    "battleMessage": "ゴブリンがあらわれた！計算で打ち負かせ！"
  },
  {
    "id": 6,
    "unit": "正負の数",
    "difficulty": "easy",
    "question": "絶対値が5の数はどれ？",
    "choices": ["5だけ", "5と−5", "−5だけ", "0"],
    "answer": "5と−5",
    "explanation": "絶対値とは数直線上の0からの距離のこと。5も−5も0から距離5なので、どちらも絶対値は5。",
    "exp": 15,
    "levelRecommended": 1,
    "enemyType": "ゴブリン",
    "battleMessage": "ゴブリンが「どっちが5だ！」とさけんでいる。正しく答えよう！"
  },
  {
    "id": 7,
    "unit": "正負の数",
    "difficulty": "easy",
    "question": "(−3) × (−4) はいくつ？",
    "choices": ["12", "−12", "7", "−7"],
    "answer": "12",
    "explanation": "負×負はプラスになります。3×4＝12なので、(−3)×(−4)＝＋12。",
    "exp": 15,
    "levelRecommended": 2,
    "enemyType": "オーク",
    "battleMessage": "オークが盾を構えた！魔法で貫け！"
  },
  {
    "id": 8,
    "unit": "正負の数",
    "difficulty": "easy",
    "question": "−2 より大きい整数のうち、最も小さいものは？",
    "choices": ["−3", "−1", "0", "1"],
    "answer": "−1",
    "explanation": "−2より大きい整数：−1, 0, 1, … の中で最も小さいのは−1です。",
    "exp": 15,
    "levelRecommended": 2,
    "enemyType": "オーク",
    "battleMessage": "オークが数直線を切り刻もうとしている！正しい数を選んで守れ！"
  },
  {
    "id": 9,
    "unit": "正負の数",
    "difficulty": "normal",
    "question": "2 − (−5) はいくつ？",
    "choices": ["3", "−3", "7", "−7"],
    "answer": "7",
    "explanation": "引き算でマイナスを引くと、プラスになります。2−(−5)＝2＋5＝7。",
    "exp": 20,
    "levelRecommended": 3,
    "enemyType": "トロール",
    "battleMessage": "トロールがあばれだした！計算の力で止めよう！"
  },
  {
    "id": 10,
    "unit": "正負の数",
    "difficulty": "normal",
    "question": "(−2)³ はいくつ？",
    "choices": ["8", "−8", "6", "−6"],
    "answer": "−8",
    "explanation": "(−2)³＝(−2)×(−2)×(−2)。まず(−2)×(−2)＝4、次に4×(−2)＝−8。",
    "exp": 25,
    "levelRecommended": 3,
    "enemyType": "トロール",
    "battleMessage": "トロールの3連撃に対抗せよ！冪乗の力を使おう！"
  },
  {
    "id": 11,
    "unit": "正負の数",
    "difficulty": "normal",
    "question": "ある日の最高気温は3℃、最低気温は−5℃でした。1日の気温差は何℃？",
    "choices": ["2℃", "8℃", "−2℃", "15℃"],
    "answer": "8℃",
    "explanation": "気温差は最高気温から最低気温を引きます。3−(−5)＝3＋5＝8℃。",
    "exp": 25,
    "levelRecommended": 4,
    "enemyType": "アイスドラゴン",
    "battleMessage": "アイスドラゴンが現れた！温度差の魔法で立ち向かえ！"
  },

  // ===== 文字式 (easy: 12-17, normal: 18-21) =====
  {
    "id": 12,
    "unit": "文字式",
    "difficulty": "easy",
    "question": "3x + 2x を計算すると？",
    "choices": ["5x", "6x", "5x²", "3x²"],
    "answer": "5x",
    "explanation": "同じ文字xが付いた数どうしをたします。3x＋2x＝(3＋2)x＝5x。",
    "exp": 15,
    "levelRecommended": 2,
    "enemyType": "スライムキング",
    "battleMessage": "スライムキングが仲間を呼んだ！文字の力でまとめてやっつけよう！"
  },
  {
    "id": 13,
    "unit": "文字式",
    "difficulty": "easy",
    "question": "a × a × a を文字式で表すと？",
    "choices": ["3a", "a³", "a+3", "3a²"],
    "answer": "a³",
    "explanation": "同じ文字をかけ合わせるときは指数を使います。a×a×a＝a³（aの3乗）。",
    "exp": 15,
    "levelRecommended": 2,
    "enemyType": "スライムキング",
    "battleMessage": "スライムキングが3つに分裂した！指数の魔法でまとめて封じよう！"
  },
  {
    "id": 14,
    "unit": "文字式",
    "difficulty": "easy",
    "question": "5 × x を文字式の書き方にすると？",
    "choices": ["x5", "5x", "5+x", "x÷5"],
    "answer": "5x",
    "explanation": "数と文字のかけ算は記号×を省略し、数を文字の前に書きます。5×x＝5x。",
    "exp": 10,
    "levelRecommended": 2,
    "enemyType": "ゴブリン魔導士",
    "battleMessage": "ゴブリン魔導士が記号で惑わせようとしている！正しい書き方を見抜け！"
  },
  {
    "id": 15,
    "unit": "文字式",
    "difficulty": "easy",
    "question": "x = 3 のとき、2x + 1 の値は？",
    "choices": ["5", "7", "9", "8"],
    "answer": "7",
    "explanation": "x＝3を代入します。2×3＋1＝6＋1＝7。",
    "exp": 15,
    "levelRecommended": 2,
    "enemyType": "ゴブリン魔導士",
    "battleMessage": "魔導士が「xに3を入れてみろ！」と叫んでいる。計算で答えよ！"
  },
  {
    "id": 16,
    "unit": "文字式",
    "difficulty": "easy",
    "question": "4a − a を計算すると？",
    "choices": ["3a", "4", "3", "5a"],
    "answer": "3a",
    "explanation": "aは1aと同じです。4a−1a＝(4−1)a＝3a。",
    "exp": 15,
    "levelRecommended": 3,
    "enemyType": "オークウォーリア",
    "battleMessage": "オークウォーリアが盾を4枚持ってきた！1枚奪って3枚にしよう！"
  },
  {
    "id": 17,
    "unit": "文字式",
    "difficulty": "easy",
    "question": "1辺がa cmの正方形の周の長さを文字式で表すと？",
    "choices": ["4a", "a²", "4+a", "2a"],
    "answer": "4a",
    "explanation": "正方形の周の長さ＝1辺×4。したがって a×4＝4a cm。",
    "exp": 15,
    "levelRecommended": 3,
    "enemyType": "オークウォーリア",
    "battleMessage": "オークウォーリアが正方形の城砦を建て始めた！周の長さを求めて弱点を探せ！"
  },
  {
    "id": 18,
    "unit": "文字式",
    "difficulty": "normal",
    "question": "3(x + 2) を展開すると？",
    "choices": ["3x + 2", "3x + 6", "3x + 5", "x + 6"],
    "answer": "3x + 6",
    "explanation": "分配法則を使います。3×x＋3×2＝3x＋6。()の中の全てに3をかけます。",
    "exp": 20,
    "levelRecommended": 4,
    "enemyType": "マジシャン",
    "battleMessage": "マジシャンがかっこの中に魔法をこめた！展開して力を解き放て！"
  },
  {
    "id": 19,
    "unit": "文字式",
    "difficulty": "normal",
    "question": "2a + 3b − a + b を計算すると？",
    "choices": ["a + 4b", "3a + 4b", "a + 2b", "3a + 2b"],
    "answer": "a + 4b",
    "explanation": "同じ文字でまとめます。aの項：2a−a＝a、bの項：3b＋b＝4b。よって a＋4b。",
    "exp": 20,
    "levelRecommended": 4,
    "enemyType": "マジシャン",
    "battleMessage": "マジシャンが2種類の魔力をまぜた！同じ種類でまとめて整理しよう！"
  },
  {
    "id": 20,
    "unit": "文字式",
    "difficulty": "normal",
    "question": "x = −2 のとき、x² − 3x の値は？",
    "choices": ["10", "−10", "−2", "2"],
    "answer": "10",
    "explanation": "x＝−2を代入。(−2)²−3×(−2)＝4−(−6)＝4＋6＝10。",
    "exp": 25,
    "levelRecommended": 5,
    "enemyType": "ダークナイト",
    "battleMessage": "ダークナイトが負の数で守りを固めた！代入の力で突き破れ！"
  },
  {
    "id": 21,
    "unit": "文字式",
    "difficulty": "normal",
    "question": "りんごが1個a円、みかんが1個b円のとき、りんご3個とみかん5個の合計金額を文字式で表すと？",
    "choices": ["3a + 5b", "8ab", "3a × 5b", "15ab"],
    "answer": "3a + 5b",
    "explanation": "りんご3個の代金は3a円、みかん5個の代金は5b円。合計は3a＋5b円。",
    "exp": 25,
    "levelRecommended": 5,
    "enemyType": "ダークナイト",
    "battleMessage": "ダークナイトが市場を占拠した！買い物の合計を文字式で計算して取り戻せ！"
  },

  // ===== 1次方程式 (easy: 22-26, normal: 27-31, hard: 32-33) =====
  {
    "id": 22,
    "unit": "1次方程式",
    "difficulty": "easy",
    "question": "x + 3 = 7 のとき、x はいくつ？",
    "choices": ["3", "4", "10", "−4"],
    "answer": "4",
    "explanation": "両辺から3を引きます。x＋3−3＝7−3 → x＝4。",
    "exp": 15,
    "levelRecommended": 3,
    "enemyType": "ゾンビ",
    "battleMessage": "ゾンビが迫ってくる！方程式を解いて封印の魔法を撃て！"
  },
  {
    "id": 23,
    "unit": "1次方程式",
    "difficulty": "easy",
    "question": "2x = 10 のとき、x はいくつ？",
    "choices": ["2", "5", "20", "8"],
    "answer": "5",
    "explanation": "両辺を2で割ります。2x÷2＝10÷2 → x＝5。",
    "exp": 15,
    "levelRecommended": 3,
    "enemyType": "ゾンビ",
    "battleMessage": "ゾンビの群れをxの魔力で分けて倒せ！"
  },
  {
    "id": 24,
    "unit": "1次方程式",
    "difficulty": "easy",
    "question": "x − 4 = 3 のとき、x はいくつ？",
    "choices": ["1", "7", "−1", "−7"],
    "answer": "7",
    "explanation": "両辺に4を加えます。x−4＋4＝3＋4 → x＝7。",
    "exp": 15,
    "levelRecommended": 3,
    "enemyType": "スケルトン",
    "battleMessage": "スケルトンが盾を持って立ちはだかる！方程式を解いて砕け！"
  },
  {
    "id": 25,
    "unit": "1次方程式",
    "difficulty": "easy",
    "question": "3x − 1 = 8 のとき、x はいくつ？",
    "choices": ["2", "3", "7", "−3"],
    "answer": "3",
    "explanation": "まず両辺に1を加えると3x＝9。次に両辺を3で割るとx＝3。",
    "exp": 20,
    "levelRecommended": 4,
    "enemyType": "スケルトン",
    "battleMessage": "スケルトンウォーリアが現れた！2段階の計算で打ち倒せ！"
  },
  {
    "id": 26,
    "unit": "1次方程式",
    "difficulty": "easy",
    "question": "4x + 2 = 10 のとき、x はいくつ？",
    "choices": ["2", "3", "−2", "1"],
    "answer": "2",
    "explanation": "両辺から2を引くと4x＝8。both辺を4で割るとx＝2。",
    "exp": 20,
    "levelRecommended": 4,
    "enemyType": "ウルフ",
    "battleMessage": "ウルフが吠えた！方程式の力で怯ませろ！"
  },
  {
    "id": 27,
    "unit": "1次方程式",
    "difficulty": "normal",
    "question": "2x + 5 = x + 9 のとき、x はいくつ？",
    "choices": ["4", "−4", "14", "2"],
    "answer": "4",
    "explanation": "xを左辺に移項すると2x−x＝9−5 → x＝4。",
    "exp": 25,
    "levelRecommended": 5,
    "enemyType": "ウェアウルフ",
    "battleMessage": "ウェアウルフが両側から挟み撃ちにしてくる！移項の技を使え！"
  },
  {
    "id": 28,
    "unit": "1次方程式",
    "difficulty": "normal",
    "question": "3(x − 2) = 9 のとき、x はいくつ？",
    "choices": ["5", "−1", "3", "7"],
    "answer": "5",
    "explanation": "まず展開すると3x−6＝9。両辺に6を加えると3x＝15。x＝5。",
    "exp": 25,
    "levelRecommended": 5,
    "enemyType": "ウェアウルフ",
    "battleMessage": "ウェアウルフが3倍の力で攻撃！展開して方程式を解け！"
  },
  {
    "id": 29,
    "unit": "1次方程式",
    "difficulty": "normal",
    "question": "ある数xの2倍から5を引いた数は11になる。方程式で表してxを求めると？",
    "choices": ["x＝3", "x＝8", "x＝11", "x＝6"],
    "answer": "x＝8",
    "explanation": "「xの2倍から5を引くと11」を式にすると2x−5＝11。2x＝16なのでx＝8。",
    "exp": 30,
    "levelRecommended": 6,
    "enemyType": "サイクロプス",
    "battleMessage": "サイクロプスが謎かけをしてきた！文章を式にして解け！"
  },
  {
    "id": 30,
    "unit": "1次方程式",
    "difficulty": "normal",
    "question": "x/2 + 1 = 4 のとき、x はいくつ？",
    "choices": ["6", "10", "2", "8"],
    "answer": "6",
    "explanation": "両辺から1を引くとx/2＝3。両辺に2をかけるとx＝6。",
    "exp": 25,
    "levelRecommended": 5,
    "enemyType": "サイクロプス",
    "battleMessage": "サイクロプスが半分の力を隠した！分数の方程式で引き出せ！"
  },
  {
    "id": 31,
    "unit": "1次方程式",
    "difficulty": "normal",
    "question": "1本80円の鉛筆をx本買ったら、代金は400円だった。xはいくつ？",
    "choices": ["4本", "5本", "6本", "3本"],
    "answer": "5本",
    "explanation": "80×x＝400という方程式をつくります。x＝400÷80＝5。鉛筆は5本。",
    "exp": 30,
    "levelRecommended": 6,
    "enemyType": "バンディット",
    "battleMessage": "バンディットが鉛筆を盗んだ！何本盗まれたか方程式で調べよう！"
  },
  {
    "id": 32,
    "unit": "1次方程式",
    "difficulty": "hard",
    "question": "5x − 3 = 2x + 9 のとき、x はいくつ？",
    "choices": ["4", "−4", "2", "6"],
    "answer": "4",
    "explanation": "xを左辺にまとめると5x−2x＝9＋3 → 3x＝12 → x＝4。",
    "exp": 35,
    "levelRecommended": 7,
    "enemyType": "ドラゴン",
    "battleMessage": "ドラゴンが現れた！強力な方程式攻撃で倒せ！"
  },
  {
    "id": 33,
    "unit": "1次方程式",
    "difficulty": "hard",
    "question": "兄の年齢は弟の年齢の2倍より3歳少ない。兄の年齢が13歳のとき、弟の年齢は何歳？",
    "choices": ["5歳", "8歳", "10歳", "6歳"],
    "answer": "8歳",
    "explanation": "弟の年齢をxとすると兄の年齢は2x−3＝13。2x＝16なのでx＝8。弟は8歳。",
    "exp": 40,
    "levelRecommended": 8,
    "enemyType": "ドラゴン",
    "battleMessage": "ドラゴンが年齢のナゾなぞを出した！方程式で解き明かせ！"
  },

  // ===== 比例と反比例 (easy: 34-37, normal: 38-41, hard: 42-43) =====
  {
    "id": 34,
    "unit": "比例と反比例",
    "difficulty": "easy",
    "question": "y = 3x のとき、x = 4 なら y はいくつ？",
    "choices": ["7", "12", "1", "3"],
    "answer": "12",
    "explanation": "x＝4を代入します。y＝3×4＝12。",
    "exp": 15,
    "levelRecommended": 4,
    "enemyType": "マーマン",
    "battleMessage": "マーマンが深海から現れた！比例の力でやっつけよう！"
  },
  {
    "id": 35,
    "unit": "比例と反比例",
    "difficulty": "easy",
    "question": "y が x に比例し、x = 2 のとき y = 8 である。比例定数はいくつ？",
    "choices": ["2", "4", "6", "16"],
    "answer": "4",
    "explanation": "y＝ax と表せます。8＝a×2なのでa＝4。比例定数は4。",
    "exp": 15,
    "levelRecommended": 4,
    "enemyType": "マーマン",
    "battleMessage": "マーマンが比例定数の謎を守っている！解き明かして進め！"
  },
  {
    "id": 36,
    "unit": "比例と反比例",
    "difficulty": "easy",
    "question": "y = 12/x のとき、x = 3 なら y はいくつ？",
    "choices": ["4", "9", "36", "15"],
    "answer": "4",
    "explanation": "x＝3を代入します。y＝12÷3＝4。",
    "exp": 15,
    "levelRecommended": 5,
    "enemyType": "シーサーペント",
    "battleMessage": "シーサーペントが現れた！反比例の魔法で向かい打て！"
  },
  {
    "id": 37,
    "unit": "比例と反比例",
    "difficulty": "easy",
    "question": "y = 2x のグラフはどんな形？",
    "choices": ["原点を通る直線", "曲線", "横に真っ直ぐな直線", "縦に真っ直ぐな直線"],
    "answer": "原点を通る直線",
    "explanation": "y＝ax（aは定数）のグラフは原点を通る直線になります。",
    "exp": 15,
    "levelRecommended": 4,
    "enemyType": "シーサーペント",
    "battleMessage": "シーサーペントがグラフの幻を作り出した！正しいグラフを見極めよ！"
  },
  {
    "id": 38,
    "unit": "比例と反比例",
    "difficulty": "normal",
    "question": "y が x に反比例し、x = 6 のとき y = 4 である。x = 8 のとき y はいくつ？",
    "choices": ["3", "5", "48", "2"],
    "answer": "3",
    "explanation": "反比例はy＝a/x。4＝a/6よりa＝24。y＝24/8＝3。",
    "exp": 25,
    "levelRecommended": 6,
    "enemyType": "ネプチューン",
    "battleMessage": "ネプチューンが嵐を呼んだ！反比例の方程式で嵐を鎮めよ！"
  },
  {
    "id": 39,
    "unit": "比例と反比例",
    "difficulty": "normal",
    "question": "時速60kmで走る車がx時間進んだとき、距離y kmを比例式で表すと？",
    "choices": ["y = 60x", "y = x/60", "y = 60/x", "y = 60+x"],
    "answer": "y = 60x",
    "explanation": "距離＝速さ×時間なので、y＝60×x＝60x。xが増えるとyも増える比例です。",
    "exp": 25,
    "levelRecommended": 6,
    "enemyType": "ネプチューン",
    "battleMessage": "ネプチューンの船が迫ってくる！速さと距離の比例式を使え！"
  },
  {
    "id": 40,
    "unit": "比例と反比例",
    "difficulty": "normal",
    "question": "面積が24cm²の長方形の縦xcm、横ycmのとき、yをxの式で表すと？",
    "choices": ["y = 24x", "y = 24/x", "y = x + 24", "y = 24 − x"],
    "answer": "y = 24/x",
    "explanation": "縦×横＝面積なので x×y＝24。yについて解くとy＝24/x。これは反比例です。",
    "exp": 25,
    "levelRecommended": 7,
    "enemyType": "ゴーレム",
    "battleMessage": "ゴーレムが長方形の床を封鎖した！反比例の式で壁を突破せよ！"
  },
  {
    "id": 41,
    "unit": "比例と反比例",
    "difficulty": "normal",
    "question": "y = −2x のグラフの特徴として正しいものは？",
    "choices": ["右上がりの直線", "右下がりの直線", "上向きの曲線", "下向きの曲線"],
    "answer": "右下がりの直線",
    "explanation": "y＝axで a<0（マイナス）のとき、グラフは右下がりの直線になります。",
    "exp": 25,
    "levelRecommended": 6,
    "enemyType": "ゴーレム",
    "battleMessage": "ゴーレムが右下から攻撃してくる！グラフの形を見極めて避けよ！"
  },
  {
    "id": 42,
    "unit": "比例と反比例",
    "difficulty": "hard",
    "question": "y が x に比例し、x = −3 のとき y = 9 である。y = −6 のとき x はいくつ？",
    "choices": ["2", "−2", "18", "−18"],
    "answer": "2",
    "explanation": "9＝a×(−3)よりa＝−3。よってy＝−3x。−6＝−3xよりx＝2。",
    "exp": 35,
    "levelRecommended": 8,
    "enemyType": "フェニックス",
    "battleMessage": "不死鳥フェニックスが現れた！比例定数を見つけて魔法の矢を放て！"
  },
  {
    "id": 43,
    "unit": "比例と反比例",
    "difficulty": "hard",
    "question": "反比例 y = a/x のグラフが点(−2, 6)を通るとき、a の値は？",
    "choices": ["−12", "12", "3", "−3"],
    "answer": "−12",
    "explanation": "点(−2, 6)を代入すると6＝a/(−2)。両辺に(−2)をかけるとa＝−12。",
    "exp": 40,
    "levelRecommended": 9,
    "enemyType": "フェニックス",
    "battleMessage": "フェニックスが座標をバラバラにした！点を代入して定数を解き明かせ！"
  },

  // ===== 図形 (easy: 44-46, normal: 47-49, hard: 50) =====
  {
    "id": 44,
    "unit": "図形",
    "difficulty": "easy",
    "question": "半径5cmの円の面積は何cm²？（π＝3.14とする）",
    "choices": ["31.4cm²", "78.5cm²", "25cm²", "15.7cm²"],
    "answer": "78.5cm²",
    "explanation": "円の面積＝半径×半径×π＝5×5×3.14＝78.5cm²。",
    "exp": 15,
    "levelRecommended": 4,
    "enemyType": "ゴーストナイト",
    "battleMessage": "ゴーストナイトが円形の盾で防いでいる！面積を計算して貫け！"
  },
  {
    "id": 45,
    "unit": "図形",
    "difficulty": "easy",
    "question": "正三角形の内角の和は何度？",
    "choices": ["90°", "120°", "180°", "360°"],
    "answer": "180°",
    "explanation": "三角形の内角の和はいつも180°です。正三角形も三角形なので180°。",
    "exp": 10,
    "levelRecommended": 3,
    "enemyType": "ゴーストナイト",
    "battleMessage": "ゴーストナイトが三角形の陣形を組んだ！内角の和で突破せよ！"
  },
  {
    "id": 46,
    "unit": "図形",
    "difficulty": "easy",
    "question": "直径10cmの円の周の長さ（円周）は何cm？（π＝3.14とする）",
    "choices": ["31.4cm", "62.8cm", "15.7cm", "78.5cm"],
    "answer": "31.4cm",
    "explanation": "円周＝直径×π＝10×3.14＝31.4cm。半径5cmなので円周＝2×5×3.14でも同じ。",
    "exp": 15,
    "levelRecommended": 4,
    "enemyType": "スフィンクス",
    "battleMessage": "スフィンクスが円形の迷宮を作った！円周を計算して脱出せよ！"
  },
  {
    "id": 47,
    "unit": "図形",
    "difficulty": "normal",
    "question": "1辺が6cmの正方形の面積は何cm²？",
    "choices": ["12cm²", "36cm²", "24cm²", "48cm²"],
    "answer": "36cm²",
    "explanation": "正方形の面積＝1辺×1辺＝6×6＝36cm²。",
    "exp": 20,
    "levelRecommended": 5,
    "enemyType": "スフィンクス",
    "battleMessage": "スフィンクスが正方形の罠を仕掛けた！面積を計算して罠を解除せよ！"
  },
  {
    "id": 48,
    "unit": "図形",
    "difficulty": "normal",
    "question": "底面の半径3cm、高さ10cmの円柱の体積は何cm³？（π＝3.14とする）",
    "choices": ["282.6cm³", "94.2cm³", "30cm³", "565.2cm³"],
    "answer": "282.6cm³",
    "explanation": "円柱の体積＝底面積×高さ＝(3×3×3.14)×10＝28.26×10＝282.6cm³。",
    "exp": 30,
    "levelRecommended": 7,
    "enemyType": "ジャイアント",
    "battleMessage": "ジャイアントが円柱の柱を武器にした！体積の魔法で粉砕せよ！"
  },
  {
    "id": 49,
    "unit": "図形",
    "difficulty": "normal",
    "question": "四角形の内角の和は何度？",
    "choices": ["180°", "270°", "360°", "540°"],
    "answer": "360°",
    "explanation": "四角形は三角形2つに分けられます。三角形の内角の和180°×2＝360°。",
    "exp": 20,
    "levelRecommended": 5,
    "enemyType": "ジャイアント",
    "battleMessage": "ジャイアントが四角形の城を建てた！内角の和で城の弱点を探せ！"
  },
  {
    "id": 50,
    "unit": "図形",
    "difficulty": "hard",
    "question": "底面の半径4cm、高さ9cmの円錐の体積は何cm³？（π＝3.14とする）",
    "choices": ["150.72cm³", "452.16cm³", "200.96cm³", "100.48cm³"],
    "answer": "150.72cm³",
    "explanation": "円錐の体積＝（底面積×高さ）÷3＝(4×4×3.14×9)÷3＝452.16÷3＝150.72cm³。",
    "exp": 45,
    "levelRecommended": 10,
    "enemyType": "魔王",
    "battleMessage": "魔王があらわれた！最後の難問で必殺技を放て！"
  }
];

// レベルテーブル（Lv1〜10）
const LEVEL_TABLE = [
  { level: 1,  expRequired: 0,   title: "見習い旅人",     bonus: "ヒント1回使える" },
  { level: 2,  expRequired: 50,  title: "冒険者",         bonus: "コンボボーナス+5%" },
  { level: 3,  expRequired: 120, title: "戦士見習い",     bonus: "不正解時の経験値+5" },
  { level: 4,  expRequired: 220, title: "正規戦士",       bonus: "ヒント2回使える" },
  { level: 5,  expRequired: 350, title: "熟練戦士",       bonus: "コンボボーナス+10%" },
  { level: 6,  expRequired: 520, title: "騎士",           bonus: "復習スキップ1回使える" },
  { level: 7,  expRequired: 730, title: "上級騎士",       bonus: "ヒント3回使える" },
  { level: 8,  expRequired: 990, title: "勇者候補",       bonus: "コンボボーナス+20%" },
  { level: 9,  expRequired: 1300, title: "伝説の勇者",   bonus: "全スキル解放" },
  { level: 10, expRequired: 1700, title: "数学の覇者",   bonus: "称号「数学の達人」獲得" }
];

// エクスポート
if (typeof module !== 'undefined') {
  module.exports = { QUESTIONS, LEVEL_TABLE };
}
